name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/python-app:${{ github.sha }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE .
          docker tag $IMAGE ${{ secrets.DOCKERHUB_USERNAME }}/python-app:latest

      - name: Push Docker Images
        run: |
          docker push $IMAGE
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/python-app:latest

      - name: Verify Cluster Access
        run: |
          kubectl get nodes

      - name: Deploy or Update Application
        run: |
          if kubectl get deployment python-app >/dev/null 2>&1; then
            echo "Deployment exists. Updating image..."
            kubectl set image deployment/python-app   python-app=$IMAGE

            kubectl rollout status deployment/python-app
          else
            echo "Deployment does not exist. Creating deployment..."

            kubectl create deployment python-app --image=$IMAGE

            kubectl expose deployment python-app  --type=NodePort  --port=5000   --target-port=5000

            kubectl rollout status deployment/python-app
          fi
            
